### ISSUE TITLE
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED when running latest docker image

### ISSUE THREAD

**Issue by Jacketbg** [LibreTranslate/LibreTranslate#836]
Hi team,
I am trying to run the latest docker image from the documentation here: https://docs.libretranslate.com/guides/installation/

```docker compose -f docker-compose.cuda.yml up -d --build```

I also tried pulling the latest container `libretranslate/libretranslate:latest-cuda` with portainer. Both times I have the same issue. The containers run properly until I try to translate any text longer than 1-2 sentences and from any language to English. This is the error in `docker logs`:

```
WARNING:waitress.queue:Task queue depth is 1
ERROR:libretranslate.app:Exception on /translate [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/dist-packages/libretranslate/app.py", line 404, in time_func
    return func(*a, **kw)
  File "/usr/local/lib/python3.8/dist-packages/libretranslate/app.py", line 378, in func
    return f(*a, **kw)
  File "/usr/local/lib/python3.8/dist-packages/libretranslate/app.py", line 831, in translate
    raise e
  File "/usr/local/lib/python3.8/dist-packages/libretranslate/app.py", line 815, in translate
    hypotheses = translator.hypotheses(q, num_alternatives + 1)
  File "/usr/local/lib/python3.8/dist-packages/argostranslate/translate.py", line 296, in hypotheses
    translated_paragraph = self.underlying.hypotheses(
  File "/usr/local/lib/python3.8/dist-packages/argostranslate/translate.py", line 173, in hypotheses
    apply_packaged_translation(
  File "/usr/local/lib/python3.8/dist-packages/argostranslate/translate.py", line 464, in apply_packaged_translation
    translated_batches = translator.translate_batch(
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
```

My host environment is the following:

- **OS**: Debian 12 (kernel 6.12.32+bpo-amd64)
- **CPU**: AMD Ryzen 9 9900X
- **GPU**: nVidia RTX 5090 32GB
- **Docker version**: 28.3.2, build 578ccf6
- **nVidia container toolkit**: 1.17.8
- **CUDA version**: 12.8

I am successfully running other docker containers using the GPU for other tasks (LLMs using pytorch, etc.).
Is this a known issue and can I do something to mitigate it?

P.S. it works as expected with very short sentences:

```
# OK
root@aigis:/opt/libretranslate-cuda# curl -X POST http://localhost:5001/translate -d q="Une équipe de chercheurs." -d source=fr -d target=en
{"translatedText":"A team of researchers."}

# OK
root@aigis:/opt/libretranslate-cuda# curl -X POST http://localhost:5001/translate -d q="Une équipe de chercheurs. Une équipe de chercheurs." -d source=fr -d target=en
{"translatedText":"A team of researchers. A team of researchers."}

# CRASHED
root@aigis:/opt/libretranslate-cuda# curl -X POST http://localhost:5001/translate -d q="Une équipe de chercheurs. Une équipe de chercheurs. Une équipe de chercheurs." -d source=fr -d target=en
{"error":"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."}
```

**Comment by Muxelmann** [comment]
I have the same problem (using docker image `libretranslate/libretranslate:latest-cuda`):

```
  checkpoint = torch.load(filename, lambda storage, loc: storage)
ERROR:libretranslate.app:Exception on /translate [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/dist-packages/libretranslate/app.py", line 404, in time_func
    return func(*a, **kw)
  File "/usr/local/lib/python3.8/dist-packages/libretranslate/app.py", line 378, in func
    return f(*a, **kw)
  File "/usr/local/lib/python3.8/dist-packages/libretranslate/app.py", line 852, in translate
    raise e
  File "/usr/local/lib/python3.8/dist-packages/libretranslate/app.py", line 836, in translate
    hypotheses = translator.hypotheses(q, num_alternatives + 1)
  File "/usr/local/lib/python3.8/dist-packages/argostranslate/translate.py", line 296, in hypotheses
    translated_paragraph = self.underlying.hypotheses(
  File "/usr/local/lib/python3.8/dist-packages/argostranslate/translate.py", line 173, in hypotheses
    apply_packaged_translation(
  File "/usr/local/lib/python3.8/dist-packages/argostranslate/translate.py", line 464, in apply_packaged_translation
    translated_batches = translator.translate_batch(
RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
```

According to [this](https://github.com/OpenNMT/CTranslate2/issues/1865) thread, the RTX50xx GPUs seem not to support all compute types. Maybe this problem can be resolved by changing it?

**Comment by webcicle** [comment]
I had the same issue with my 5070ti and solved it by upgrading pytorch to nightly with cu128 (also requires ubuntu22.04). Then it will automatically convert the model weights to float16 and there is no error.

**Comment by pierotofy** [comment]
This should be fixed with the latest version.

**Comment by baoc75** [comment]
Thanks for the update! I just tested with latest-cuda Docker image today on RTX Pro 2000 Blackwell. 
Something like this will throw that exception: https://website.com/?source=en&target=vi&q=Oh%2C+and+before+you+leave+today%2C+please+sign+up+for+our+mailing+list+to+stay+informed+of+future+lectures.
